export type Resultado = "L" | "E" | "V";

export type QuinielaPayloadV1 = {
  v: 1;
  n: string;
  p: [number, Resultado, number, number][];
};

export const FALTA_QUINIELA = 'FALTA_QUINIELA';
export const QUINIELA_CORRUPTA_O_INVALIDA = 'QUINIELA_CORRUPTA_O_INVALIDA';
export const VERSION_DE_QUINIELA_NO_SOPORTADA = 'VERSION_DE_QUINIELA_NO_SOPORTADA';
export const DATOS_DE_QUINIELA_INVALIDOS = 'DATOS_DE_QUINIELA_INVALIDOS';
export const PARTIDO_DUPLICADO_EN_QUINIELA = 'PARTIDO_DUPLICADO_EN_QUINIELA';
export const PARTIDO_DESCONOCIDO_EN_QUINIELA = 'PARTIDO_DESCONOCIDO_EN_QUINIELA';
export const RESULTADO_Y_MARCADOR_INCOHERENTES = 'RESULTADO_Y_MARCADOR_INCOHERENTES';
